apiVersion: v1
kind: Secret
metadata:
  name: noiroze-secret
  namespace: default
type: Opaque
data:
  aws_access_key: QUtJQTVWWlRJQU9KVE5OWFdCUEk=
  aws_secret_key: NG9MWTVEWmN3LzhsYllBRVg2MGxnZjNvTXJXcUZJaWhXZWpqS1FBaA==

